### ISSUE TITLE
scalikejdbc-play-support 2.8.0-scalikejdbc-3.5 can not use with scalikejdbc version 4.0.0

### ISSUE THREAD

**Issue by KingHO2359** [scalikejdbc/scalikejdbc-play-support#228]
Hi @seratch , would you like to build scalikejdbc-play-support 2.8.0-scalikejdbc version 4.0.0-RC1?

Because scalikejdbc-play-support 3.5 can not use with scalikejdbc 4.0.0 when we do not override DEFAULT_NAME

This commit https://github.com/scalikejdbc/scalikejdbc-play-support/commit/cd005eeee4009cfba1a11bc33144fa440db3892f is solved

Thank you so much.

**Comment by seratch** [comment]
Hi @KingHO2359, thanks for raising this issue. I just released version 2.8.0-scalikejdbc-4.0 onto the Sonatype OSS repositories. The jar files will be synchronized to the Maven Central repos soon.
