### ISSUE TITLE
Support for different Connection Pools

### ISSUE THREAD

**Issue by Uxio0** [scalikejdbc/scalikejdbc-play-support#25]
Would it be possible to have connection pool configurable (I'm interested on using HikariCP, which is now integrated in Play Framework)?

http://scalikejdbc.org/documentation/connection-pool.html

**Comment by seratch** [comment]
Try scalikejdbc-dbapi-adapter.

http://scalikejdbc.org/documentation/playframework-support.html

**Comment by Uxio0** [comment]
Thanks! But I'm not sure yet about the difference of dbapi-adapter and scalikejdbc-play-initializer. The documentation just covers the two options but not in detail.

**Comment by seratch** [comment]
scalikejdbc-dbapi-adapter just uses a datasource prepared by Play's db configurion. Indeed, the documentation can be improved.

**Comment by Uxio0** [comment]
I wouldn't mind to do it, but at first I need to understand it more.

So I assume **scalikejdbc-play-initializer** uses their own pool managed by scalike (DBCP) and **scalikejdbc-dbapi-adapter** uses play configuration (so it will use HikariCP by default). Any other difference (configuration or so)?

**Comment by seratch** [comment]
No other difference.

**Comment by Uxio0** [comment]
Thanks!

Kind regards!
