### ISSUE TITLE
publish for scala 2.12, play 2.6

### ISSUE THREAD

**Issue by benoit-ponsero** [scalikejdbc/scalikejdbc-play-support#27]
Play team has just released their first milestone for scala 2.12. 

It would be great to have a 2.12 version for testing.

**Comment by xuwei-k** [comment]
depends on https://github.com/flyway/flyway-play/issues/46 ( [in example project](https://github.com/scalikejdbc/scalikejdbc-play-support/blob/b3363876ecdd3b29f15bab7e9b7f02cfab9176ee/build.sbt#L94) )

**Comment by xuwei-k** [comment]
- https://oss.sonatype.org/content/repositories/releases/org/scalikejdbc/scalikejdbc-play-fixture_2.12/
- https://github.com/scalikejdbc/scalikejdbc-play-support/commit/4244f1f5b5616c81e096133d9c567f7cd201eee1
