### ISSUE TITLE
Support Scalikejdbc 3

### ISSUE THREAD

**Issue by Uxio0** [scalikejdbc/scalikejdbc-play-support#32]
When I try to update Scalike to 3.0.1 I get the following errors, either using Play 2.5 or Play 2.6 (Scala 2.11). I'm using scalikejdbc-play-dbapi-adapter 2.6.0:

`Error injecting constructor, java.lang.NoSuchMethodError: scalikejdbc.DataSourceConnectionPool.<init>(Ljavax/sql/DataSource;Lscalikejdbc/DataSourceConnectionPoolSettings;)V
  at scalikejdbc.PlayDBApiAdapter.<init>(PlayDBApiAdapter.scala:30)
  at scalikejdbc.PlayDBApiAdapterModule.bindings(PlayDBApiAdapterModule.scala:26):
Binding(class scalikejdbc.PlayDBApiAdapter to self eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating scalikejdbc.PlayDBApiAdapter`

Kind regards

**Comment by seratch** [comment]
Currently, the version depends on scalikejdbc 2.5.x. scalikejdbc 2.5 and 3.0 are not bin-compatible. We should consider releasing for scalikejdbc 3 users as well.

**Comment by Uxio0** [comment]
Oh ok, thanks! Would it be difficult to compile for scalikejdbc 3?

**Comment by xuwei-k** [comment]
- https://github.com/scalikejdbc/scalikejdbc-play-support/releases/tag/2.6.0-scalikejdbc-3.1
- https://repo1.maven.org/maven2/org/scalikejdbc/scalikejdbc-play-initializer_2.12/
