### ISSUE TITLE
Support hikaricp?

### ISSUE THREAD

**Issue by prurph** [scalikejdbc/scalikejdbc-play-support#34]
Any chance of supporting hikaricp? Maybe through `db.name.pool = hikaricp`?

It looks like it might be fairly straightforward; I'd consider giving the implementation a shot if this is something you're open to.

**Comment by prurph** [comment]
Hmmmm actually I think I misunderstood how this works. Play uses hikari by default, so it looks like this should just respect that I think?

Sorry for the confusion.

**Comment by seratch** [comment]
Try scalikejdbc-dbapi-adapter. You can use all Play's standard configuration with it.

**Comment by seratch** [comment]
Let me close this issue. If you have any questions on how to use scalikejdbc-dbapi-adapter, feel free to ask me here.
