### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc-play-support#58]
playframework 2.7.3 will support Scala 2.13

- [x] https://github.com/flyway/flyway-play/pull/73 only use example project

**Comment by xuwei-k** [comment]
https://github.com/scalikejdbc/scalikejdbc-play-support/commit/24a5bd151fcce8a8edfe3bd59e0ee320364acea3

**Comment by xuwei-k** [comment]
https://github.com/scalikejdbc/scalikejdbc-play-support/commit/93ef47a042795cc493a268a0ecc2e11c8371ce6d

**Comment by xuwei-k** [comment]
@seratch please publish new version with Scala 2.13 support 🙏

**Comment by seratch** [comment]
Done. https://oss.sonatype.org/content/groups/staging/org/scalikejdbc/scalikejdbc-play-initializer_2.13/2.7.1-scalikejdbc-3.3/
