### ISSUE TITLE
2.7.0-scalikejdbc-3.4 depends on scalikejdbc 3.3.5

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc-play-support#65]
https://github.com/scalikejdbc/scalikejdbc-play-support/commit/7b02d18f321922cf19a0eb9727d3bb2a13c97964#diff-fdc3abdfd754eeb24090dbd90aeec2ceR1 😢

**Comment by seratch** [comment]
ah, my bad.

**Comment by seratch** [comment]
2.7.1-scalikejdbc-3.4 is available.
